# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack
- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies
- script: |
    export PATH=$HOME/.local/bin:$PATH
    # Build the package, its tests, and its docs and run the tests
    stack test
  displayName: Test Package
